#### 原始网页：https://news.qq.com/zt2020/page/feiyan.htm#/
### 1. 数据提取部分

#### 1.1 导入模块

##### 如果使用本地静态资源，需要在头部声明

In [1]:
# # 只需要在顶部声明 CurrentConfig.ONLINE_HOST 即可(针对notebook)
# from pyecharts.globals import CurrentConfig, OnlineHostType
# # OnlineHostType.NOTEBOOK_HOST 默认值为 http://localhost:8888/nbextensions/assets/
# CurrentConfig.ONLINE_HOST = OnlineHostType.NOTEBOOK_HOST

In [2]:
import requests
import json
import time
import datetime
import pandas as pd

In [3]:
today = datetime.datetime.today()
date = f'{today.year}年{today.month}月{today.day}日'
date

'2021年8月2日'

#### 1.2 获取数据

In [4]:
url = f"https://view.inews.qq.com/g2/getOnsInfo?name=disease_h5&'{int(time.time()*1000)}'" 
response = requests.get(url)
datas = json.loads(response.json()['data'])
china_datas = datas['areaTree'][0]['children']
china_datas[:1]

[{'name': '台湾',
  'today': {'confirm': 28,
   'confirmCuts': 0,
   'isUpdated': True,
   'tip': '',
   'wzz_add': 0},
  'total': {'nowConfirm': 2029,
   'confirm': 15702,
   'suspect': 0,
   'dead': 789,
   'deadRate': '5.02',
   'showRate': False,
   'heal': 12884,
   'healRate': '82.05',
   'showHeal': True,
   'wzz': 0},
  'children': [{'name': '地区待确认',
    'today': {'confirm': 28, 'confirmCuts': 0, 'isUpdated': True},
    'total': {'nowConfirm': 2029,
     'confirm': 15702,
     'suspect': 0,
     'dead': 789,
     'deadRate': '5.02',
     'showRate': False,
     'heal': 12884,
     'healRate': '82.05',
     'showHeal': True,
     'wzz': 0}}]}]

#### 1.3 解析提取数据

In [5]:
data_set = []
for data in china_datas:
    data_dict = {
        'province': data['name'], 
        'nowConfirm': data['total']['nowConfirm'], 
        'confirm': data['total']['confirm'], 
        'dead': data['total']['dead'], 
        'heal': data['total']['heal'], 
        'deadRate': data['total']['deadRate'], 
        'healRate': data['total']['healRate'],
    } 
    data_set.append(data_dict)

#### 1.4 生成表格对象

In [6]:
df = pd.DataFrame(data_set) 
df

   province  nowConfirm  confirm  dead   heal deadRate healRate
0        台湾        2029    15702   789  12884     5.02    82.05
1        云南         381      831     2    448     0.24    53.91
2        江苏         297     1041     0    744     0.00    71.47
3        广东          69     2886     8   2809     0.28    97.33
4        上海          61     2314     7   2246     0.30    97.06
5        香港          60    11987   212  11715     1.77    97.73
6        四川          43     1154     3   1108     0.26    96.01
7        福建          41      741     1    699     0.13    94.33
8        河南          31     1347    22   1294     1.63    96.07
9        陕西          24      659     3    632     0.46    95.90
10       天津          22      425     3    400     0.71    94.12
11       湖南          22     1090     4   1064     0.37    97.61
12       湖北          21    68198  4512  63665     6.62    93.35
13       北京          19     1095     9   1067     0.82    97.44
14       浙江          18     1396     1   1377     0.07    98.64
15       辽宁           9      437     2    426     0.46    97.48
16      内蒙古           9      408     1    398     0.25    97.55
17       山东           6      889     7    876     0.79    98.54
18       澳门           5       59     0     54     0.00    91.53
19       甘肃           4      199     2    193     1.01    96.98
20       重庆           4      603     6    593     1.00    98.34
21       广西           2      277     2    273     0.72    98.56
22       宁夏           1       77     0     76     0.00    98.70
23       海南           1      189     6    182     3.17    96.30
24       吉林           1      574     3    570     0.52    99.30
25       贵州           0      147     2    145     1.36    98.64
26       山西           0      253     0    253     0.00   100.00
27       西藏           0        1     0      1     0.00   100.00
28       青海           0       18     0     18     0.00   100.00
29       河北           0     1317     7   1310     0.53    99.47
30       新疆           0      980     3    977     0.31    99.69
31      黑龙江           0     1612    13   1599     0.81    99.19
32       安徽           0     1008     6   1002     0.60    99.40
33       江西           0      937     1    936     0.11    99.89

#### 1.5 数据永久性保存

In [7]:
df.to_csv('./国内疫情数据.csv', encoding='utf-8-sig')

### 2. 可视化操作部分

#### 2.1 导入模块

In [8]:
from pyecharts import options as opts
from pyecharts.charts import Bar, Line, Pie, Grid, Map

#### 2.2 数据整理

In [9]:
df1 = df.sort_values(by=['nowConfirm'], ascending=False)[:10]
df1

  province  nowConfirm  confirm  dead   heal deadRate healRate
0       台湾        2029    15702   789  12884     5.02    82.05
1       云南         381      831     2    448     0.24    53.91
2       江苏         297     1041     0    744     0.00    71.47
3       广东          69     2886     8   2809     0.28    97.33
4       上海          61     2314     7   2246     0.30    97.06
5       香港          60    11987   212  11715     1.77    97.73
6       四川          43     1154     3   1108     0.26    96.01
7       福建          41      741     1    699     0.13    94.33
8       河南          31     1347    22   1294     1.63    96.07
9       陕西          24      659     3    632     0.46    95.90

#### 2.3 可视化饼图

##### 提示：可视化前，将数据转换为列表

In [10]:
lst = [list(i) for i in zip(df1['province'].values.tolist(),
                            df1['nowConfirm'].values.tolist())]
lst

[['台湾', 2029],
 ['云南', 381],
 ['江苏', 297],
 ['广东', 69],
 ['上海', 61],
 ['香港', 60],
 ['四川', 43],
 ['福建', 41],
 ['河南', 31],
 ['陕西', 24]]

In [11]:
pie = (
    Pie()
    .add("", lst, radius=["10%", "30%"])
    .set_global_opts(
        title_opts=opts.TitleOpts(title=f'{date}_省份占比'),
        legend_opts=opts.LegendOpts(orient="vertical", pos_top="70%", pos_left="70%"))
    .set_series_opts(label_opts=opts.LabelOpts(formatter="{b}:{c}")))
pie.render_notebook()

#### 2.4可视化地图

In [12]:
df3 = df.sort_values(by=['nowConfirm'], ascending=False)[0:]
df3 = df3.drop(df3[df3['nowConfirm'] == 0].index)
lst = [list(i) for i in zip(df3['province'].values.tolist(),
                            df3['nowConfirm'].values.tolist())]
map = (
    Map()
    .add("", lst, 'china')
    .set_global_opts(
        title_opts=opts.TitleOpts(title=f'{date}_疫情分布'),
        visualmap_opts=opts.VisualMapOpts(
            max_=1000,
            min_=0,
            is_piecewise=False)
    )
    .set_series_opts(label_opts=opts.LabelOpts(is_show=False))
)
map.render_notebook()