### 1. 数据提取部分

#### 1.1 导入模块

In [1]:
import requests
import json
import time
import pandas as pd

#### 1.2 获取数据

In [2]:
url = f"https://view.inews.qq.com/g2/getOnsInfo?name=disease_h5&'{int(time.time()*1000)}'" 
response = requests.get(url)
datas = json.loads(response.json()['data'])
china_datas = datas['areaTree'][0]['children']
china_datas[:1]

[{'name': '台湾',
  'today': {'confirm': 46,
   'confirmCuts': 0,
   'isUpdated': True,
   'tip': '',
   'wzz_add': 0},
  'total': {'nowConfirm': 142,
   'confirm': 1256,
   'suspect': 0,
   'dead': 12,
   'deadRate': '0.96',
   'showRate': False,
   'heal': 1102,
   'healRate': '87.74',
   'showHeal': True,
   'wzz': 0},
  'children': [{'name': '地区待确认',
    'today': {'confirm': 46, 'confirmCuts': 0, 'isUpdated': True},
    'total': {'nowConfirm': 142,
     'confirm': 1256,
     'suspect': 0,
     'dead': 12,
     'deadRate': '0.96',
     'showRate': False,
     'heal': 1102,
     'healRate': '87.74',
     'showHeal': True,
     'wzz': 0}}]}]

#### 1.3 解析提取数据

In [3]:
data_set = []
for data in china_datas:
    data_dict = {
        'province': data['name'], 
        'nowConfirm': data['total']['nowConfirm'], 
        'confirm': data['total']['confirm'], 
        'dead': data['total']['dead'], 
        'heal': data['total']['heal'], 
        'deadRate': data['total']['deadRate'], 
        'healRate': data['total']['healRate'],
    } 
    data_set.append(data_dict)

#### 1.4 生成表格对象

In [4]:
df = pd.DataFrame(data_set) 
df

   province  nowConfirm  confirm  dead   heal deadRate healRate
0        台湾         142     1256    12   1102     0.96    87.74
1        香港          96    11817   210  11511     1.78    97.41
2        上海          58     2025     7   1960     0.35    96.79
3        广东          54     2383     8   2321     0.34    97.40
4        云南          39      348     2    307     0.57    88.22
5        四川          29      999     3    967     0.30    96.80
6        浙江          23     1347     1   1323     0.07    98.22
7        福建          21      597     1    575     0.17    96.31
8        海南          17      188     6    165     3.19    87.77
9        陕西          10      597     3    584     0.50    97.82
10       江苏           8      721     0    713     0.00    98.89
11       山西           7      251     0    244     0.00    97.21
12       重庆           7      598     6    585     1.00    97.83
13       天津           7      388     3    378     0.77    97.42
14       广西           6      275     2    267     0.73    97.09
15       湖北           6    68158  4512  63640     6.62    93.37
16       湖南           4     1046     4   1038     0.38    99.24
17      内蒙古           4      383     1    378     0.26    98.69
18       山东           3      881     7    871     0.79    98.86
19       北京           2     1057     9   1046     0.85    98.96
20       宁夏           1       76     0     75     0.00    98.68
21       河南           1     1312    22   1289     1.68    98.25
22       澳门           0       49     0     49     0.00   100.00
23       西藏           0        1     0      1     0.00   100.00
24       安徽           0      994     6    988     0.60    99.40
25       甘肃           0      193     2    191     1.04    98.96
26       青海           0       18     0     18     0.00   100.00
27       辽宁           0      408     2    406     0.49    99.51
28       新疆           0      980     3    977     0.31    99.69
29       贵州           0      147     2    145     1.36    98.64
30       江西           0      937     1    936     0.11    99.89
31       吉林           0      573     3    570     0.52    99.48
32       河北           0     1317     7   1310     0.53    99.47
33      黑龙江           0     1610    13   1597     0.81    99.19

#### 1.5 数据永久性保存

In [5]:
df.to_csv('./国内疫情数据.csv', encoding='gbk')

### 2. 可视化操作部分

#### 2.1 导入模块

In [6]:
from pyecharts import options as opts
from pyecharts.charts import Bar, Line, Pie, Grid, Map

#### 2.2 数据整理

In [7]:
df1 = df.sort_values(by=['nowConfirm'], ascending=False)[:10]
df1

  province  nowConfirm  confirm  dead   heal deadRate healRate
0       台湾         142     1256    12   1102     0.96    87.74
1       香港          96    11817   210  11511     1.78    97.41
2       上海          58     2025     7   1960     0.35    96.79
3       广东          54     2383     8   2321     0.34    97.40
4       云南          39      348     2    307     0.57    88.22
5       四川          29      999     3    967     0.30    96.80
6       浙江          23     1347     1   1323     0.07    98.22
7       福建          21      597     1    575     0.17    96.31
8       海南          17      188     6    165     3.19    87.77
9       陕西          10      597     3    584     0.50    97.82

#### 2.3 可视化饼图

##### 提示：可视化前，将数据转换为列表

In [8]:
lst = [list(i) for i in zip(df1['province'].values.tolist(),
                            df1['nowConfirm'].values.tolist())]
lst

[['台湾', 142],
 ['香港', 96],
 ['上海', 58],
 ['广东', 54],
 ['云南', 39],
 ['四川', 29],
 ['浙江', 23],
 ['福建', 21],
 ['海南', 17],
 ['陕西', 10]]

In [9]:
pie = (
    Pie()
    .add("", lst, radius=["10%", "30%"])
    .set_global_opts(
        title_opts=opts.TitleOpts(title=' '),
        legend_opts=opts.LegendOpts(orient="vertical", pos_top="70%", pos_left="70%"))
    .set_series_opts(label_opts=opts.LabelOpts(formatter="{b}:{c}")))
pie.render_notebook()

#### 2.4可视化地图

In [10]:
df3 = df.sort_values(by=['nowConfirm'], ascending=False)[0:]
df3 = df3.drop(df3[df3['nowConfirm'] == 0].index)
lst = [list(i) for i in zip(df3['province'].values.tolist(),
                            df3['nowConfirm'].values.tolist())]
map = (
    Map()
    .add("", lst, 'china')
    .set_global_opts(
        title_opts=opts.TitleOpts(title=' '),
        visualmap_opts=opts.VisualMapOpts(
            max_=1000,
            min_=0,
            is_piecewise=False)
    )
    .set_series_opts(label_opts=opts.LabelOpts(is_show=False))
)
map.render_notebook()