#### 原始网页：https://news.qq.com/zt2020/page/feiyan.htm#/
### 1. 数据提取部分

#### 1.1 导入模块

In [1]:
import requests
import json
import time
import datetime
import pandas as pd

In [2]:
today = datetime.datetime.today()
date = f'{today.year}年{today.month}月{today.day}日'
date

'2021年6月18日'

#### 1.2 获取数据

In [3]:
url = f"https://view.inews.qq.com/g2/getOnsInfo?name=disease_h5&'{int(time.time()*1000)}'" 
response = requests.get(url)
datas = json.loads(response.json()['data'])
china_datas = datas['areaTree'][0]['children']
china_datas[:1]

[{'name': '台湾',
  'today': {'confirm': 362,
   'confirmCuts': 0,
   'isUpdated': True,
   'tip': '',
   'wzz_add': 0},
  'total': {'nowConfirm': 12120,
   'confirm': 13771,
   'suspect': 0,
   'dead': 518,
   'deadRate': '3.76',
   'showRate': False,
   'heal': 1133,
   'healRate': '8.23',
   'showHeal': True,
   'wzz': 0},
  'children': [{'name': '地区待确认',
    'today': {'confirm': 362, 'confirmCuts': 0, 'isUpdated': True},
    'total': {'nowConfirm': 12120,
     'confirm': 13771,
     'suspect': 0,
     'dead': 518,
     'deadRate': '3.76',
     'showRate': False,
     'heal': 1133,
     'healRate': '8.23',
     'showHeal': True,
     'wzz': 0}}]}]

#### 1.3 解析提取数据

In [4]:
data_set = []
for data in china_datas:
    data_dict = {
        'province': data['name'], 
        'nowConfirm': data['total']['nowConfirm'], 
        'confirm': data['total']['confirm'], 
        'dead': data['total']['dead'], 
        'heal': data['total']['heal'], 
        'deadRate': data['total']['deadRate'], 
        'healRate': data['total']['healRate'],
    } 
    data_set.append(data_dict)

#### 1.4 生成表格对象

In [5]:
df = pd.DataFrame(data_set) 
df

   province  nowConfirm  confirm  dead   heal deadRate healRate
0        台湾       12120    13771   518   1133     3.76     8.23
1        广东         216     2666     8   2442     0.30    91.60
2        上海          74     2173     7   2092     0.32    96.27
3        香港          68    11881   210  11603     1.77    97.66
4        浙江          41     1376     1   1334     0.07    96.95
5        福建          40      646     1    605     0.15    93.65
6        云南          32      382     2    348     0.52    91.10
7        四川          31     1057     3   1023     0.28    96.78
8        江苏          18      739     0    721     0.00    97.56
9        陕西          15      622     3    604     0.48    97.11
10       北京          15     1072     9   1048     0.84    97.76
11       天津          11      399     3    385     0.75    96.49
12      内蒙古           6      393     1    386     0.25    98.22
13       河南           3     1316    22   1291     1.67    98.10
14       辽宁           3      426     2    421     0.47    98.83
15       重庆           3      598     6    589     1.00    98.49
16       湖南           1     1051     4   1046     0.38    99.52
17       湖北           1    68160  4512  63647     6.62    93.38
18       山西           1      253     0    252     0.00    99.60
19       山东           1      883     7    875     0.79    99.09
20       澳门           1       52     0     51     0.00    98.08
21       海南           1      188     6    181     3.19    96.28
22       宁夏           1       76     0     75     0.00    98.68
23       青海           0       18     0     18     0.00   100.00
24       安徽           0     1004     6    998     0.60    99.40
25       广西           0      275     2    273     0.73    99.27
26       新疆           0      980     3    977     0.31    99.69
27       吉林           0      573     3    570     0.52    99.48
28      黑龙江           0     1612    13   1599     0.81    99.19
29       江西           0      937     1    936     0.11    99.89
30       西藏           0        1     0      1     0.00   100.00
31       河北           0     1317     7   1310     0.53    99.47
32       贵州           0      147     2    145     1.36    98.64
33       甘肃           0      194     2    192     1.03    98.97

#### 1.5 数据永久性保存

In [6]:
df.to_csv('./国内疫情数据.csv', encoding='gbk')

### 2. 可视化操作部分

#### 2.1 导入模块

In [7]:
from pyecharts import options as opts
from pyecharts.charts import Bar, Line, Pie, Grid, Map

#### 2.2 数据整理

In [8]:
df1 = df.sort_values(by=['nowConfirm'], ascending=False)[:10]
df1

   province  nowConfirm  confirm  dead   heal deadRate healRate
0        台湾       12120    13771   518   1133     3.76     8.23
1        广东         216     2666     8   2442     0.30    91.60
2        上海          74     2173     7   2092     0.32    96.27
3        香港          68    11881   210  11603     1.77    97.66
4        浙江          41     1376     1   1334     0.07    96.95
5        福建          40      646     1    605     0.15    93.65
6        云南          32      382     2    348     0.52    91.10
7        四川          31     1057     3   1023     0.28    96.78
8        江苏          18      739     0    721     0.00    97.56
10       北京          15     1072     9   1048     0.84    97.76

#### 2.3 可视化饼图

##### 提示：可视化前，将数据转换为列表

In [9]:
lst = [list(i) for i in zip(df1['province'].values.tolist(),
                            df1['nowConfirm'].values.tolist())]
lst

[['台湾', 12120],
 ['广东', 216],
 ['上海', 74],
 ['香港', 68],
 ['浙江', 41],
 ['福建', 40],
 ['云南', 32],
 ['四川', 31],
 ['江苏', 18],
 ['北京', 15]]

In [10]:
pie = (
    Pie()
    .add("", lst, radius=["10%", "30%"])
    .set_global_opts(
        title_opts=opts.TitleOpts(title=f'{date}_省份占比'),
        legend_opts=opts.LegendOpts(orient="vertical", pos_top="70%", pos_left="70%"))
    .set_series_opts(label_opts=opts.LabelOpts(formatter="{b}:{c}")))
pie.render_notebook()

#### 2.4可视化地图

In [11]:
df3 = df.sort_values(by=['nowConfirm'], ascending=False)[0:]
df3 = df3.drop(df3[df3['nowConfirm'] == 0].index)
lst = [list(i) for i in zip(df3['province'].values.tolist(),
                            df3['nowConfirm'].values.tolist())]
map = (
    Map()
    .add("", lst, 'china')
    .set_global_opts(
        title_opts=opts.TitleOpts(title=f'{date}_疫情分布'),
        visualmap_opts=opts.VisualMapOpts(
            max_=1000,
            min_=0,
            is_piecewise=False)
    )
    .set_series_opts(label_opts=opts.LabelOpts(is_show=False))
)
map.render_notebook()